[build]
builder = "DOCKERFILE"
buildCommand = "npm install && npm run build: css"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 100
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}

