[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:css"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[nixpacks]