[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:css"

[deploy]
startCommand = "python main.py"
healthcheckPath = "null"
restartPolicyType = "ON_FAILURE"

[nixpacks]
framework = ["python", "nodejs"] 